/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_998511_5[] = { 0, 6, 12 };

// (before - mean) / scale
const float ei_classifier_anom_scale_998511_5[3] = { 5441.27384909682, 2440.3854872613415, 2231.084795768775 };
const float ei_classifier_anom_mean_998511_5[3] = { 4096.090320607167, 2906.6181683585955, 4062.0296959669568 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_998511_5[32] = {
	{ ( float[3] ) { -0.7224790453910828, -1.0970022678375244, 0.6233378648757935 }, 0.08441427511366047 },
	{ ( float[3] ) { 1.951336145401001, 0.49833863973617554, -0.3277342617511749 }, 0.4920774326352114 },
	{ ( float[3] ) { -0.31476980447769165, -0.774939239025116, 1.7774595022201538 }, 0.24255106326242137 },
	{ ( float[3] ) { -0.5777390599250793, -0.9494442939758301, 0.6217020153999329 }, 0.24505761448481267 },
	{ ( float[3] ) { -0.5046249628067017, 1.6039917469024658, -1.3852825164794922 }, 0.30833993863162795 },
	{ ( float[3] ) { 0.0034269157331436872, -0.2995900511741638, 0.6403335332870483 }, 0.26982191416237494 },
	{ ( float[3] ) { -0.3294859230518341, 1.5589271783828735, -0.9437604546546936 }, 0.9218501936738793 },
	{ ( float[3] ) { 1.800087809562683, 0.6877146363258362, -1.1557148694992065 }, 0.5596162280541289 },
	{ ( float[3] ) { 2.3131113052368164, 1.3370471000671387, -0.18086311221122742 }, 0.3836775013404093 },
	{ ( float[3] ) { 1.607431411743164, 1.13979971408844, -0.32011911273002625 }, 0.5321628011166452 },
	{ ( float[3] ) { 2.1643974781036377, 1.2176893949508667, -0.8428255915641785 }, 0.5484835909254956 },
	{ ( float[3] ) { -0.6252762675285339, 0.7798464894294739, -1.5339688062667847 }, 0.21580658517816798 },
	{ ( float[3] ) { -0.1386481374502182, -0.5485769510269165, 0.6390668153762817 }, 0.25413071431372775 },
	{ ( float[3] ) { 2.25026535987854, 0.8556092977523804, -1.210753321647644 }, 0.4696811630507012 },
	{ ( float[3] ) { -0.5014069080352783, -0.5562965273857117, 0.7615343928337097 }, 0.30220159825107845 },
	{ ( float[3] ) { 2.302046537399292, 0.5309757590293884, -0.9911972284317017 }, 0.3585510030855777 },
	{ ( float[3] ) { -0.5475558042526245, 1.294448733329773, -1.3633570671081543 }, 0.2446484206160188 },
	{ ( float[3] ) { 2.488126039505005, 0.4202326536178589, -0.5955080986022949 }, 0.4598836755053181 },
	{ ( float[3] ) { 1.6404038667678833, 0.23001982271671295, -0.9709069728851318 }, 0.5161979820518047 },
	{ ( float[3] ) { -0.2909194231033325, 2.113562822341919, -0.7043531537055969 }, 0.33850517377024764 },
	{ ( float[3] ) { 0.8222032785415649, 0.7004461884498596, -0.28678181767463684 }, 0.6917898769284361 },
	{ ( float[3] ) { -0.4263494312763214, 1.1487069129943848, -0.8862656354904175 }, 0.396156996727225 },
	{ ( float[3] ) { -0.5663892030715942, -0.8191332817077637, 0.9451079368591309 }, 0.29470947007114123 },
	{ ( float[3] ) { 1.607155203819275, 0.057540614157915115, -0.17421582341194153 }, 0.4309892607862618 },
	{ ( float[3] ) { -0.4934096336364746, 0.9138386249542236, -1.4058717489242554 }, 0.46943033124306743 },
	{ ( float[3] ) { 2.220841884613037, 1.6923772096633911, -0.8657114505767822 }, 0.4168886940508847 },
	{ ( float[3] ) { -0.020870011299848557, 0.33314645290374756, 0.6203452944755554 }, 0.15224645111009122 },
	{ ( float[3] ) { -0.33819150924682617, 1.9104454517364502, -1.1049197912216187 }, 0.29807262172546123 },
	{ ( float[3] ) { -0.3003136217594147, -0.846526026725769, 2.031703233718872 }, 0.2250068207855557 },
	{ ( float[3] ) { -0.20429331064224243, -0.7448629140853882, 1.4127882719039917 }, 0.26088114571956583 },
	{ ( float[3] ) { -0.3609752655029297, 1.7794017791748047, -0.3928273618221283 }, 0.4356904464582134 },
	{ ( float[3] ) { 1.1853893995285034, 2.178352117538452, -0.4076194167137146 }, 0.6245224050352312 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
